name: 'Upload a Release Asset'
description: 'Upload a release asset to an existing release on your repository'
author: 'GitHub'
inputs:
  upload_url:
    description: 'The URL for uploading assets to the release'
    required: true
  files:
    description: 'The path to the asset you want to upload'
    required: true
outputs:
  browser_download_url:
    description: 'The URL users can navigate to in order to download the uploaded asset'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
